In [1]:
# Import Required Packages 
import pandas as pd
import numpy as np
import pandas_profiling
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn 
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [22]:
#Approach by uploading the fiel to jupyter using read_csv
data = pd.read_csv(r"HR_comma_sep.csv")

In [23]:
data_100 = data.sample(100)

In [24]:
data_100.drop(['left'], axis=1)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,department,salary
12018,0.45,0.51,2,160,3,1,1,sales,low
9240,0.19,1.00,4,188,4,1,0,marketing,medium
2472,0.97,0.63,3,133,3,0,0,hr,low
11049,0.65,0.83,4,251,2,0,0,technical,medium
4539,0.85,0.51,3,261,4,0,1,technical,medium
14970,0.78,0.93,4,225,5,0,0,sales,medium
4913,0.90,0.72,5,237,2,0,0,accounting,low
7995,0.70,0.85,3,161,2,0,0,technical,medium
744,0.39,0.52,2,134,3,0,0,technical,low
7746,0.55,0.49,2,180,5,1,0,technical,low
4002,0.34,0.85,4,123,4,0,0,hr,medium
901,0.43,0.53,2,145,3,0,0,IT,low
10186,0.75,0.89,5,154,4,0,0,hr,low
5219,0.55,0.80,4,260,3,0,0,hr,high
11048,0.29,0.39,6,105,6,0,0,technical,medium
1947,0.72,0.84,5,257,5,0,0,technical,medium
5813,0.95,0.67,4,227,3,0,0,sales,low
5545,0.21,0.92,2,211,2,0,0,support,medium
14592,0.38,0.46,2,145,3,0,0,hr,medium
6398,0.66,0.70,5,254,2,0,0,IT,medium
1528,0.41,0.56,2,160,3,0,0,sales,low
12595,0.09,0.87,5,263,4,0,0,IT,low
1220,0.36,0.52,2,137,3,0,0,marketing,low
13870,0.15,0.81,5,280,3,1,0,RandD,high
9745,0.15,0.95,4,251,5,0,0,support,high
3295,0.74,0.86,3,186,3,1,0,sales,high
13208,0.51,0.58,4,140,2,1,0,product_mng,low
7962,0.74,0.54,4,167,2,0,0,sales,medium
12148,0.84,0.88,4,263,5,1,0,marketing,low
12681,0.40,0.49,2,128,3,0,0,sales,low
...,...,...,...,...,...,...,...,...,...
4262,0.76,0.56,3,154,2,0,0,IT,low
5945,0.37,0.74,5,117,3,0,0,product_mng,medium
13451,0.78,0.89,4,272,2,0,0,support,low
519,0.39,0.51,2,129,3,0,0,IT,low
9598,0.79,0.72,5,245,3,1,0,technical,low
10182,0.91,0.70,6,201,2,1,0,accounting,low
6930,0.58,0.78,3,223,3,0,0,management,low
9941,0.96,0.72,3,157,3,0,0,sales,medium
10427,0.71,0.76,3,134,3,1,0,support,low
4955,0.93,0.66,4,228,3,0,0,RandD,low
2331,0.82,0.83,3,271,2,0,0,technical,medium
5594,0.37,0.45,6,100,5,1,0,sales,medium
9322,0.70,0.74,3,212,3,0,0,sales,low
373,0.36,0.57,2,142,3,0,0,product_mng,medium
454,0.09,0.97,7,254,4,1,0,RandD,medium
9859,0.72,0.67,3,243,3,0,0,sales,low
5669,0.89,0.94,5,223,3,0,0,sales,medium
11766,0.76,0.85,3,192,3,0,0,marketing,low
2200,0.89,0.53,5,272,3,0,0,IT,low
9949,0.89,0.64,4,274,2,1,0,sales,low
8799,0.92,0.95,6,239,4,0,0,sales,medium
2358,0.93,0.82,4,175,3,0,0,IT,low
13977,0.76,0.85,3,192,3,0,0,marketing,low
9862,0.75,0.93,4,195,3,0,0,sales,medium
14093,0.60,0.45,3,104,4,0,0,IT,low
137,0.42,0.48,2,129,3,0,0,management,low
2137,0.52,0.43,2,199,2,0,0,sales,medium
7325,0.78,0.87,3,183,4,0,0,RandD,low
4855,0.92,0.62,4,196,3,0,0,support,medium
11566,0.57,0.55,4,177,8,0,0,sales,low

In [25]:
data_100.to_csv('HR_sample.csv')

In [3]:
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
satisfaction_level       14999 non-null float64
last_evaluation          14999 non-null float64
number_project           14999 non-null int64
average_montly_hours     14999 non-null int64
time_spend_company       14999 non-null int64
Work_accident            14999 non-null int64
left                     14999 non-null int64
promotion_last_5years    14999 non-null int64
department               14999 non-null object
salary                   14999 non-null object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [5]:
data_cat = data.select_dtypes('object')

In [6]:
data_cat

       department  salary
0           sales     low
1           sales  medium
2           sales  medium
3           sales     low
4           sales     low
5           sales     low
6           sales     low
7           sales     low
8           sales     low
9           sales     low
10          sales     low
11          sales     low
12          sales     low
13          sales     low
14          sales     low
15          sales     low
16          sales     low
17          sales     low
18          sales     low
19          sales     low
20          sales     low
21          sales     low
22          sales     low
23          sales     low
24          sales     low
25          sales     low
26          sales     low
27          sales     low
28     accounting     low
29     accounting     low
...           ...     ...
14969       sales  medium
14970       sales  medium
14971       sales  medium
14972  accounting  medium
14973  accounting  medium
14974  accounting  medium
14975          hr  medium
14976          hr  medium
14977          hr  medium
14978          hr  medium
14979   technical  medium
14980   technical    high
14981   technical     low
14982   technical  medium
14983   technical  medium
14984   technical  medium
14985   technical  medium
14986   technical     low
14987   technical     low
14988   technical     low
14989   technical     low
14990     support     low
14991     support     low
14992     support     low
14993     support     low
14994     support     low
14995     support     low
14996     support     low
14997     support     low
14998     support     low

[14999 rows x 2 columns]

In [7]:
# dummification by encoding 
from  sklearn.preprocessing import LabelEncoder
encoding_list = ['department','salary']
data[encoding_list] = data[encoding_list].apply(LabelEncoder().fit_transform)

In [8]:
data

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,7,1
1,0.80,0.86,5,262,6,0,1,0,7,2
2,0.11,0.88,7,272,4,0,1,0,7,2
3,0.72,0.87,5,223,5,0,1,0,7,1
4,0.37,0.52,2,159,3,0,1,0,7,1
5,0.41,0.50,2,153,3,0,1,0,7,1
6,0.10,0.77,6,247,4,0,1,0,7,1
7,0.92,0.85,5,259,5,0,1,0,7,1
8,0.89,1.00,5,224,5,0,1,0,7,1
9,0.42,0.53,2,142,3,0,1,0,7,1
10,0.45,0.54,2,135,3,0,1,0,7,1
11,0.11,0.81,6,305,4,0,1,0,7,1
12,0.84,0.92,4,234,5,0,1,0,7,1
13,0.41,0.55,2,148,3,0,1,0,7,1
14,0.36,0.56,2,137,3,0,1,0,7,1
15,0.38,0.54,2,143,3,0,1,0,7,1
16,0.45,0.47,2,160,3,0,1,0,7,1
17,0.78,0.99,4,255,6,0,1,0,7,1
18,0.45,0.51,2,160,3,1,1,1,7,1
19,0.76,0.89,5,262,5,0,1,0,7,1
20,0.11,0.83,6,282,4,0,1,0,7,1
21,0.38,0.55,2,147,3,0,1,0,7,1
22,0.09,0.95,6,304,4,0,1,0,7,1
23,0.46,0.57,2,139,3,0,1,0,7,1
24,0.40,0.53,2,158,3,0,1,0,7,1
25,0.89,0.92,5,242,5,0,1,0,7,1
26,0.82,0.87,4,239,5,0,1,0,7,1
27,0.40,0.49,2,135,3,0,1,0,7,1
28,0.41,0.46,2,128,3,0,1,0,2,1
29,0.38,0.50,2,132,3,0,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,1,0,7,2
14970,0.78,0.93,4,225,5,0,1,0,7,2
14971,0.39,0.45,2,140,3,0,1,0,7,2
14972,0.11,0.97,6,310,4,0,1,0,2,2
14973,0.36,0.52,2,143,3,0,1,0,2,2
14974,0.36,0.54,2,153,3,0,1,0,2,2
14975,0.10,0.79,7,310,4,0,1,0,3,2
14976,0.40,0.47,2,136,3,0,1,0,3,2
14977,0.81,0.85,4,251,6,0,1,0,3,2
14978,0.40,0.47,2,144,3,0,1,0,3,2
14979,0.09,0.93,6,296,4,0,1,0,9,2
14980,0.76,0.89,5,238,5,0,1,0,9,0
14981,0.73,0.93,5,162,4,0,1,0,9,1
14982,0.38,0.49,2,137,3,0,1,0,9,2
14983,0.72,0.84,5,257,5,0,1,0,9,2
14984,0.40,0.56,2,148,3,0,1,0,9,2
14985,0.91,0.99,5,254,5,0,1,0,9,2
14986,0.85,0.85,4,247,6,0,1,0,9,1
14987,0.90,0.70,5,206,4,0,1,0,9,1
14988,0.46,0.55,2,145,3,0,1,0,9,1
14989,0.43,0.57,2,159,3,1,1,0,9,1
14990,0.89,0.88,5,228,5,1,1,0,8,1
14991,0.09,0.81,6,257,4,0,1,0,8,1
14992,0.40,0.48,2,155,3,0,1,0,8,1
14993,0.76,0.83,6,293,6,0,1,0,8,1
14994,0.40,0.57,2,151,3,0,1,0,8,1
14995,0.37,0.48,2,160,3,0,1,0,8,1
14996,0.37,0.53,2,143,3,0,1,0,8,1
14997,0.11,0.96,6,280,4,0,1,0,8,1
14998,0.37,0.52,2,158,3,0,1,0,8,1

In [9]:

# Approach 2
Y= data["left"]
X = data.drop(['left'], axis=1)

In [10]:
# Train and test split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=62, stratify=Y)
x_train.shape
x_test.shape
y_train.shape
y_test.shape

(4500,)

In [11]:

from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor(max_depth = 10, n_estimators = 100, random_state = 1)

C:\Users\chait\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [14]:
forest.fit(X, Y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=10,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=1, verbose=0, warm_start=False)

In [21]:

import pickle
pickle.dump(forest, open('HR_model.pkl', 'wb'))

In [26]:
model_1 = pickle.load(open(r'C:\Users\chait\Desktop\Data Science UPX\Nestle SFTP\HR_Predictor\polls\HR_model.pkl','rb'))

In [31]:
X['Left'] = model_1.predict(X)

In [35]:
X['Left_value'] = X["Left"].apply(lambda x : 0 if x <= 0.5 else 1)

In [36]:
X

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,department,salary,Left,Left_value
0,0.38,0.53,2,157,3,0,0,7,1,0.998570,1
1,0.80,0.86,5,262,6,0,0,7,2,0.986502,1
2,0.11,0.88,7,272,4,0,0,7,2,1.000000,1
3,0.72,0.87,5,223,5,0,0,7,1,0.983140,1
4,0.37,0.52,2,159,3,0,0,7,1,0.998570,1
5,0.41,0.50,2,153,3,0,0,7,1,0.998570,1
6,0.10,0.77,6,247,4,0,0,7,1,1.000000,1
7,0.92,0.85,5,259,5,0,0,7,1,0.980815,1
8,0.89,1.00,5,224,5,0,0,7,1,0.988499,1
9,0.42,0.53,2,142,3,0,0,7,1,0.999921,1
10,0.45,0.54,2,135,3,0,0,7,1,0.999921,1
11,0.11,0.81,6,305,4,0,0,7,1,1.000000,1
12,0.84,0.92,4,234,5,0,0,7,1,0.987499,1
13,0.41,0.55,2,148,3,0,0,7,1,0.999921,1
14,0.36,0.56,2,137,3,0,0,7,1,0.999921,1
15,0.38,0.54,2,143,3,0,0,7,1,0.999921,1
16,0.45,0.47,2,160,3,0,0,7,1,0.998570,1
17,0.78,0.99,4,255,6,0,0,7,1,0.987872,1
18,0.45,0.51,2,160,3,1,1,7,1,0.998570,1
19,0.76,0.89,5,262,5,0,0,7,1,0.989689,1
20,0.11,0.83,6,282,4,0,0,7,1,1.000000,1
21,0.38,0.55,2,147,3,0,0,7,1,0.999921,1
22,0.09,0.95,6,304,4,0,0,7,1,1.000000,1
23,0.46,0.57,2,139,3,0,0,7,1,0.998882,1
24,0.40,0.53,2,158,3,0,0,7,1,0.998570,1
25,0.89,0.92,5,242,5,0,0,7,1,0.988977,1
26,0.82,0.87,4,239,5,0,0,7,1,0.985646,1
27,0.40,0.49,2,135,3,0,0,7,1,0.999921,1
28,0.41,0.46,2,128,3,0,0,2,1,0.999921,1
29,0.38,0.50,2,132,3,0,0,2,1,0.999921,1
...,...,...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,0,7,2,0.998570,1
14970,0.78,0.93,4,225,5,0,0,7,2,0.986984,1
14971,0.39,0.45,2,140,3,0,0,7,2,0.999921,1
14972,0.11,0.97,6,310,4,0,0,2,2,1.000000,1
14973,0.36,0.52,2,143,3,0,0,2,2,0.999921,1
14974,0.36,0.54,2,153,3,0,0,2,2,0.998570,1
14975,0.10,0.79,7,310,4,0,0,3,2,1.000000,1
14976,0.40,0.47,2,136,3,0,0,3,2,0.999921,1
14977,0.81,0.85,4,251,6,0,0,3,2,0.985503,1
14978,0.40,0.47,2,144,3,0,0,3,2,0.999921,1
14979,0.09,0.93,6,296,4,0,0,9,2,1.000000,1
14980,0.76,0.89,5,238,5,0,0,9,0,0.986521,1
14981,0.73,0.93,5,162,4,0,0,9,1,0.118340,0
14982,0.38,0.49,2,137,3,0,0,9,2,0.999921,1
14983,0.72,0.84,5,257,5,0,0,9,2,0.985495,1
14984,0.40,0.56,2,148,3,0,0,9,2,0.999921,1
14985,0.91,0.99,5,254,5,0,0,9,2,0.986787,1
14986,0.85,0.85,4,247,6,0,0,9,1,0.984194,1
14987,0.90,0.70,5,206,4,0,0,9,1,0.103597,0
14988,0.46,0.55,2,145,3,0,0,9,1,0.999921,1
14989,0.43,0.57,2,159,3,1,0,9,1,0.999071,1
14990,0.89,0.88,5,228,5,1,0,8,1,0.981225,1
14991,0.09,0.81,6,257,4,0,0,8,1,1.000000,1
14992,0.40,0.48,2,155,3,0,0,8,1,0.998570,1
14993,0.76,0.83,6,293,6,0,0,8,1,0.803840,1
14994,0.40,0.57,2,151,3,0,0,8,1,0.990914,1
14995,0.37,0.48,2,160,3,0,0,8,1,0.998570,1
14996,0.37,0.53,2,143,3,0,0,8,1,0.999921,1
14997,0.11,0.96,6,280,4,0,0,8,1,1.000000,1
14998,0.37,0.52,2,158,3,0,0,8,1,0.998570,1